# Copyright 2026 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

# Octo STS policy for manifest-gen dev environment
# Service account: markmcc-mfg@markmc-dev.iam.gserviceaccount.com

issuer: https://accounts.google.com
subject: "113232556405431296212"

permissions:
  # Read github actions logs
  actions: read

  # Read check status
  checks: read

  # Create and push branches
  contents: write

  # Create and update pull requests
  pull_requests: write

  # Read issues
  issues: read

  # Trigger and manage GitHub Actions workflows
  workflows: write

repositories:
  - stereo
