# Copyright 2026 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

# Octo STS policy for Materializer dev environment
# Service account: materializer@mattmoor-chainguard.iam.gserviceaccount.com

issuer: https://accounts.google.com
subject: "101531125799729172566"

permissions:
  # Read github actions logs
  actions: read

  # Read check status
  checks: read

  # Create and push branches
  contents: write

  # Create and update pull requests
  pull_requests: write

  # Read issues
  issues: read

  # Trigger and manage GitHub Actions workflows
  workflows: write

repositories:
  - stereo
