# Copyright 2026 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

# Octo STS policy for confidence bot in Joe Borg's dev environment.
# Service account: confidence@borg-chainguard-dev.iam.gserviceaccount.com

issuer: https://accounts.google.com
subject: "118047872954112399052"

permissions:
  contents: read
  pull_requests: read
  issues: write
  checks: read
