issuer: https://accounts.google.com
# eco-fixer-reconciler@prod-enforce-fabc.iam.gserviceaccount.com (102687350045478824621)
# eco-fixer-reconciler@staging-enforce-cd1e.iam.gserviceaccount.com ()
# eco-fixer-reconciler@dev-eco-jb8z.iam.gserviceaccount.com (107649951963973435701)
subject_pattern: "(102687350045478824621|107649951963973435701)"

permissions:
  checks: read
  contents: read 
  pull_requests: read 

repositories:
- ecosystems-packages
