issuer: https://accounts.google.com
# eco-fixer-reconciler@prod-enforce-fabc.iam.gserviceaccount.com (116452929344229454849)
# eco-fixer-reconciler@staging-enforce-cd1e.iam.gserviceaccount.com ()
# eco-fixer-reconciler@dev-eco-jb8z.iam.gserviceaccount.com (106272559743380954607)
subject_pattern: "(116452929344229454849|106272559743380954607)"

permissions:
  checks: read
  contents: read 
  pull_requests: read 

repositories:
- ecosystems-packages
