issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/enterprise-packages:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/enterprise-packages/.github/workflows/build.yaml@refs/heads/main

permissions:
  contents: read

repositories:
- enterprise-packages
- grafana
