issuer: https://token.actions.githubusercontent.com
# Runs presubmit and in the merge queue.
subject_pattern: repo:chainguard-dev/enterprise-packages:.*
claim_pattern:
  workflow_ref: chainguard-dev/enterprise-packages/.github/workflows/ci-build.yaml@.*

permissions:
  contents: read
  pull_requests: write # to comment in prs

repositories:
- enterprise-advisories
- enterprise-packages
- grafana
