issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/enterprise-packages:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/enterprise-packages/.github/workflows/wolfictl-update-gh.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write

# Opens pull requests against enterprise-packages.
repositories:
- enterprise-packages
- grafana
