# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://accounts.google.com
# 107106855617134891633: bot-fulfilled@staging-enforce-cd1e.iam.gserviceaccount.com
# 110008571748373383893: bot-fulfilled@prod-enforce-fabc.iam.gserviceaccount.com
subject_pattern: "(107106855617134891633|110008571748373383893)"

permissions:
  issues: read
  organization_projects: read

repositories: [] # Act over all of the repos in the org.
