# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/.github:ref:refs/heads/main
claim_pattern:
  workflow_ref: chainguard-dev/\.github/\.github/workflows/ghaudit\.yaml@refs/heads/main

permissions:
  metadata: read
  administration: read # To list deploy keys

repositories: [] # Act over all of the repos in the org.
