# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/internal:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/internal/.github/workflows/github-audit-alerter.yaml@refs/heads/main

# The permissions needed to run https://github.com/chainguard-dev/github-audit-alerter
permissions:
  administration: read
  organization_administration: read
  security_events: read

# This operates across the entire organization.
repositories: []
