issuer: https://accounts.google.com

# octo-sts/internal-tools: internal-tools-gh-rt-checker@octo-sts.iam.gserviceaccount.com
subject_pattern: "117769840195636332244"

permissions:
  contents: read

# limit the scope to only the repositories that are needed
# this service will just get the rate limit will not perform any actions in the repo
repositories:
  - .github
