issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/grafana:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/grafana/.github/workflows/cg-release.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write

# Allow for cloning submodules, and sending a PR to enterprise packages.
repositories:
- enterprise-packages
- grafana
