# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://issuer.enforce.dev

subject_pattern: .*
claim_pattern:
  email_verified: "true"
  email: .*@chainguard.dev

permissions:
  contents: read

repositories:
  - ecosystems-avro
  - ecosystems-cassandra
  - ecosystems-elasticsearch
  - ecosystems-grpc-java
  - ecosystems-hadoop
  - ecosystems-hive
  - ecosystems-kafka
  - ecosystems-libcheck
  - ecosystems-neo4j
  - ecosystems-spark
  - iamguarded-charts
  - iamguarded-containers
  - iamguarded-tools
  - zulu-jdk21u
