# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

# This policy allows Chainguard employees to access private GitHub repositories
# using `chainctl auth octo-sts`, in order to generate short-lived, tightly-scoped
# GitHub access tokens when building packages locally.

issuer: https://accounts.google.com
claim_pattern:
  email_verified: "true"
  email: .*@chainguard.dev

permissions:
  contents: read

repositories:
- chainguard-dev/ecossytems-avro
- chainguard-dev/ecosystems-cassandra
- chainguard-dev/ecosystems-elasticsearch
- chainguard-dev/ecosystems-grpc-java
- chainguard-dev/ecosystems-hadoop
- chainguard-dev/ecosystems-hive
- chainguard-dev/ecosystems-kafka
- chainguard-dev/ecosystems-libcheck
- chainguard-dev/ecosystems-neo4j
- chainguard-dev/ecosystems-spark
- chainguard-dev/iamguarded-charts
- chainguard-dev/iamguarded-containers
- chainguard-dev/iamguarded-tools
- chainguard-dev/zulu-jdk21u
