issuer: https://accounts.google.com
# devops-gh-issue-assigner@internal-tools-1ho6.iam.gserviceaccount.com
subject: "103632985228260696990"

permissions:
  issues: write

repositories:
  - internal-dev
  - customer-issues
  - image-release-stats
  - infosec
  - prodsec
