issuer: https://accounts.google.com

# POC bot for syncing GitHub project data
# Running in jrawlings2-chainguard-dev project for evaluation purposes
# Service account: 107440718730380529713
subject: "107440718730380529713"

permissions:
  organization_projects: read
  repository_projects: read
  issues: read
  pull_requests: read
  metadata: read

repositories:
  - internal-dev
