issuer: https://accounts.google.com
# autofix@mattmoor-chainguard.iam.gserviceaccount.com
subject: "113456058529792035155"

permissions:
  actions: read
  checks: write
  contents: write # Enable autofix mode
  pull_requests: read
  statuses: read
  workflows: write # Allow triggering actions when authoring commits.

repositories:
  - terraform-infra-common
  - enterprise-packages
