issuer: https://accounts.google.com
# autofix@mgreau85-chainguard.iam.gserviceaccount.com
subject: "104658657678730945684"

permissions:
  actions: read
  checks: write
  contents: write
  pull_requests: read
  statuses: read
  workflows: write # Allow triggering actions when authoring commits.

repositories:
  - terraform-infra-common
  - enterprise-packages
  - mono
