issuer: https://accounts.google.com

subject_pattern: "(103595812881446521465|104597405312073876708)"

permissions:
  actions: read
  checks: read
  contents: read
  pull_requests: read
  statuses: read

repositories:
  - .github
