issuer: https://accounts.google.com
# devops-gh-rel-notes@internal-tools-1ho6.iam.gserviceaccount.com
subject: "114300023027344329792"

permissions:
  issues: write
  pull_requests: write
  statuses: write

# This operates across the entire organization.
repositories: []
