# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

# OctoSTS policy for grype-db-builder staging service
# Provides GitHub token for vunnel to query GitHub Advisory Database API
# Token used for rate limiting (5000 req/hr vs 60 req/hr without auth)

issuer: https://accounts.google.com

# TODO: Replace with actual staging service account uniqueId after terraform creates it
# Get with: gcloud iam service-accounts list --project=staging-enforce-cd1e --format="table(uniqueId,email)" | grep grypedb
# Example: grypedb-xxxx@staging-enforce-cd1e.iam.gserviceaccount.com
subject: "REPLACE_WITH_STAGING_SA_UNIQUE_ID"

permissions:
  contents: read

# Limit scope to specific repos (security best practice)
# Even though vunnel doesn't directly access these repos, this prevents
# the policy from granting access to ALL chainguard-dev repos
repositories:
- enterprise-packages
- extra-packages
