issuer: https://accounts.google.com
# qackage@staging-enforce-cd1e.iam.gserviceaccount.com
subject: "100942902213012637818"

permissions:
  contents: read
  checks: write
  pull_requests: write # add label in PR

repositories:
  - enterprise-packages
  - stereo
