issuer: https://accounts.google.com
# autofix@staging-enforce-cd1e.iam.gserviceaccount.com
subject: "118295070799166027529"

permissions:
  checks: write
  contents: write
  pull_requests: read
  statuses: read
  workflows: write # Allow triggering actions when authoring commits.

repositories:
  - enterprise-packages
  - mono
  - terraform-infra-common
