# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/chainguard-devops:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/chainguard-devops/.github/workflows/copy-gh-users.yaml@refs/heads/main

permissions:
  contents: write # read/write file in chainguard-devops
  pull_requests: write # create PR

repositories:
  - infra
  - chainguard-devops
