issuer: https://accounts.google.com
# autofix@nghia-chainguard-ng.iam.gserviceaccount.com
subject: "108428541062587971294"

permissions:
  checks: write
  contents: write
  pull_requests: write
  statuses: read
  workflows: write # Allow triggering actions when authoring commits.

repositories:
  - terraform-infra-common
  - enterprise-packages
