# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/mattmoor-actions:ref:refs/heads/main
claim_pattern:
  # Used for testing octo-sts in actions.
  workflow_ref: chainguard-dev/mattmoor-actions/\.github/workflows/octo-sts\.yaml@refs/heads/main

permissions:
  administration: read # To list deploy keys
  checks: read
  contents: read
  issues: read
  metadata: read
  pull_requests: read
  statuses: read
  workflows: read

repositories: [] # Act over all of the repos in the org.
# - helm-charts
# - homebrew-tap
# - mattmoor-actions # private repo
